import time
import random
name = None
neighbour_name = None
inputs = []
new_inputs = []
inventory = []

def update_input (new_inputs):
    global inputs
    inputs.clear()
    inputs.extend(new_inputs)
    return inputs
def check_input (user_input):
    global new_inputs
    update_input(new_inputs)
    checked_input = input(user_input).strip().lower()
    while checked_input not in inputs:
        checked_input = input("Sorry, I didn't catch that.\n>").strip().lower()
    else:
        return checked_input
def replay():
    global name
    global new_inputs
    new_inputs = ["y", "n"]
    time.sleep(2)
    reply = check_input("Do you want to play again?\n(y/n)\n>")
    if reply == "y":
        room1()
    else:
        time.sleep(1)
        print(f"Very well. Until next time, {name}.")
        time.sleep(2)
        print("\nZombieland was developed for CodeNation by Team-JAC.")
        print("Team-JAC:")
        print("         Joe Barber")
        print("         Ann Chance")
        print("         Claudio Fabbri")
        print("\nThanks for playing!\n")

def room1():
    global name
    global new_inputs
    time.sleep(2)
    print("You are in your home.")
    time.sleep(2)
    print("You hear a news broadcast a warning that the zombie apocalypse is upon you!")
    time.sleep(2)
    print(f"What do you do {name}?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print("a: Leave the safety of your home in a bid to outrun the ravenous zombie horde.")
    time.sleep(3)
    print("b: Stay home, after all that was probably more fake news.")
    time.sleep(2)
    reply = check_input("Please choose from a or b.\n>")
    if reply == "a":
        time.sleep(1)
        print("You leave your house and take off running down the street.")
        time.sleep(3)
        print("Conveniently, you remember that your nanna owns a zombie-proof bunker up in the highlands!")
        room3()
    else:
        time.sleep(1)
        print("You lock the doors and maybe prop a chair up against the door handle. Better safe than sorry.")
        room2()
def room2():
    global name
    global new_inputs
    time.sleep(2)
    print("You hear scratching at the door. The zombie horde is upon you!")
    time.sleep(2)
    print("Wow. Of all the things for mainstream journalists to be right about, it had to be zombies...")
    time.sleep(2)
    print(f"Time to think, {name}. How will you weather the end of days?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print("a: Take your trusty rifle and fend off the bloodthirsty zombies.")
    time.sleep(3)
    reply = check_input("or b: Check the internet for some handy tips on surviving the zombie apocalypse.\n>")
    if reply == "a":
        time.sleep(1)
        print("You lock and load, leaning out of the upstairs window to take some easy potshots at the zombies.")
        time.sleep(3)
        print("You're doing well, and making a surprising dent in the horde.")
        time.sleep(2)
        print("Suddenly...")
        for i in range(3):
            i = "KNOCK"
            time.sleep(1)
            print(i)
        time.sleep(2)
        print("Just as you go to investigate, a policeman suddenly headbutts the barricade to pieces!")
        time.sleep(2)
        print("As the zombies flood into your house and fall upon you, you hear a loud voice.")
        time.sleep(2)
        print("\n\"OI OI, 'AVE YE GOT A LOICENSE FER THAT ROIFLE?\"\n")
        time.sleep(1)
        print("   ______ ")
        print("  | 0  0 |")
        print("  |_<ii>_|")
        print(" ___|  |___________ __  ")
        print("|______ ___________|__|  ")
        print("|______|__|    ")
        print("  |______|")
        print("  |      |")
        print("  |  |\\  \\ ")
        print("  |  | \\  \\")
        print("  |  |  \\  \\")
        print("  |  |_  \\  \\_")
        print("   \\___\\  \\___\\")
        print("                   ")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
    else:
        time.sleep(1)
        print("You boot up the computer and thankfully the power and internet are still on.")
        time.sleep(2)
        print("You check twitter for any news about the zombies...")
        time.sleep(3)
        print("The current trending hashtags are about the football...")
        time.sleep(2)
        print("-and something about the Kardashians.")
        time.sleep(2)
        print("That's about right.")
        time.sleep(4)
        print("You post about the invading zombies, reaching out to the wide world of social media in your time of need.")
        time.sleep(2)
        print("You hear the barricade break down just as you get banned off of Twitter for zombiephobia.")
        time.sleep(1)
        print("   ______ ")
        print("  | 0  0 |")
        print("  |_<ii>_|")
        print(" ___|  |___________ __  ")
        print("|______ ___________|__|  ")
        print("|______|__|    ")
        print("  |______|")
        print("  |      |")
        print("  |  |\\  \\ ")
        print("  |  | \\  \\")
        print("  |  |  \\  \\")
        print("  |  |_  \\  \\_")
        print("   \\___\\  \\___\\")
        print("                   ")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
def room3():
    global name
    global new_inputs
    global neighbour_name
    time.sleep(2)
    print("You head down the street roughly in the direction of the main road.")
    time.sleep(2)
    print("You hear a loud voice shouting for you.")
    time.sleep(2)
    print(f"\n\"{name}! {name}, over here!\"\n")
    time.sleep(2)
    possible_names = [
        "Englebert", 
        "Barbera", 
        "Jimothy", 
        "Liam", 
        "Fredricio", 
        "Bjorn Bjornsson", 
        "Ignacious", 
        "Despacito", 
        "Brodrick", 
        "Ronald McDonald", 
        "Glykon the All Powerful", 
        "Ned Flanders",
        "Un Deadmann",
        "Gene Eric",
        "Woderwick"
        ]
    neighbour_name = random.choice(possible_names)
    print(f"It's your neighbour, {neighbour_name}!")
    time.sleep(2)
    print(f"{neighbour_name} is offering to let you take shelter from the zombies in their home.")
    time.sleep(2)
    print(f"Truth be told, {neighbour_name} always sort of gave you the creeps...")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print(f"Do you a: Ignore {neighbour_name} and keep going?")
    time.sleep(3)
    reply = check_input(f"Or b: throw caution to the wind and join {neighbour_name} to face the horde together?\n>")
    if reply == "a":
        time.sleep(1)
        print(f"You decide to pass up {neighbour_name}'s offer and continue on your merry way.")
        time.sleep(2)
        print(f"It was probably for the best. Who knows what dark secrets {neighbour_name} was keeping...")
        room6()
    else:
        time.sleep(1)
        print(f"You figure that you stand more of a chance against the zombies joining forces with {neighbour_name}.")
        time.sleep(2)
        print(f"Either {neighbour_name} is secretly some kind of ninja who could fight all of the zombies for you,")
        time.sleep(2)
        print("or you could at the very least eat all of their Doritos when they're not looking...")
        room4()
def room4():
    global name
    global new_inputs
    time.sleep(2)
    print(f"You help {neighbour_name} barricade the front door. You finish not a minute before the zombies begin chewing on the doorbell.")
    time.sleep(2)
    print(f"\"Good job, {name}!\", {neighbour_name} says.")
    time.sleep(2)
    print(f"{neighbour_name} goes to high-five you. It is not reciprocated.")
    time.sleep(4)
    print(f"{neighbour_name} feels awkward.")
    time.sleep(2)
    print(f"It was about the moment {neighbour_name} had their hand up that you noticed a very zombillian bite-mark...")
    time.sleep(2)
    print("If watching all those episodes of The Walking Dead have taught you anything; it's that when someone is bit, they're going to turn any second...")
    time.sleep(1)
    print("-and that you should mow all the lawns like, all the time... But that's hardly relevant right now.")
    time.sleep(2)
    print(f"What do you do, {name}? Can you make the hard decisions?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print(f"a: Tap into that hour or so at work you spent learning basic first aid, and try to cure {neighbour_name}")
    time.sleep(3)
    reply = check_input(f"b: Abandon your fragile principals and steal {neighbour_name}'s supplies; leaving them behind in favour of greener, less zombified pastures?\n>")
    if reply == "a":
        time.sleep(1)
        print(f"You sit {neighbour_name} down, breaking the news to them gently. They take it better than expected.")
        time.sleep(2)
        print(f"When {neighbour_name} gets done breaking stuff, you try to fix the rapidly necrotising bite-hole.")
        time.sleep(3)
        print(f"About the time {neighbour_name} sinks their teeth into you, you realise that you're not a qualified medical professional...")
        time.sleep(1)
        print("   ______ ")
        print("  | 0  0 |")
        print("  |_<ii>_|")
        print(" ___|  |___________ __  ")
        print("|______ ___________|__|  ")
        print("|______|__|    ")
        print("  |______|")
        print("  |      |")
        print("  |  |\\  \\ ")
        print("  |  | \\  \\")
        print("  |  |  \\  \\")
        print("  |  |_  \\  \\_")
        print("   \\___\\  \\___\\")
        print("                   ")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
    else:
        time.sleep(1)
        print(f"You tell {neighbour_name} that you're going to the bathroom real quick.")
        time.sleep(2)
        print(f"{neighbour_name} asks you why you're going into the garage to use the bathroom. You tell them not to worry about it.")
        time.sleep(3)
        print(f"You lock yourself in the garage. You are surrounded by a stockpile of various supplies that {neighbour_name} was hoarding.")
        time.sleep(2)
        print(f"Is THIS why you've not been able to buy toilet paper from anywhere lately?!")
        room5()
def room5():
    global name
    global neighbour_name
    global new_inputs
    time.sleep(2)
    print("You have decided that in the name of greater cosmic justice, you are absolutely going to take a whole bunch of this stash.")
    time.sleep(2)
    print(f"Judging from the noises in the next room, sounds like {neighbour_name} is about zombified.")
    time.sleep(2)
    print("Don't suppose they would particularly mind it if you maybe took the car-?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print(f"Do you a: Go for it, forsaking the last of your morality and steal {neighbour_name}'s car,")
    time.sleep(3)
    reply = check_input(f"or b: Quietly slip out of the house, laden with supplies, and escape on foot?\n>")
    if reply == "a":
        time.sleep(1)
        print(f"As the old idiom goes, \"in for a penny, in for a pound.\"")
        time.sleep(2)
        print(f"You break into {neighbour_name}'s car and luckily the keys are in the glovebox.")
        time.sleep(2)
        print("The garage door is thankfully one of the quieter ones, so you hit the road without additional hassle.")
        room9()
    else:
        time.sleep(1)
        print(f"You decide that just because {neighbour_name} is now living-impaired, doesn't mean they don't have a right to private property...")
        time.sleep(2)
        print("-Except for all the canned food and toilet paper that you took because... Well fair's fair...")
        room6()
def room6():
    global name
    global neighbour_name
    global new_inputs
    time.sleep(2)
    print("You sneak through the back alleys and side roads until you find yourself at your local supermarket.")
    time.sleep(2)
    print("Thankfully the place looks abandoned. Guess everyone went to go loot Waitrose, leaving this perfectly good Lidl practically untouched.")
    time.sleep(2)
    print("The store's doors are open, and there are a few vehicles in the parking lot.")
    time.sleep(2)
    print("What do you want to do?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print("a: Check out the store and get some good bargains?")
    time.sleep(3)
    reply = check_input("b: Investigate the parking lot?\n>")
    if reply == "a":
        time.sleep(1)
        print("The store is huge, and they have everything!")
        time.sleep(2)
        print("Discount water, without bits! Canned bread! Assorted food-shapes, in breadcrumbs!")
        time.sleep(2)
        print("I have bargains to the left of me, deals to the right.")
        time.sleep(1)
        print("Here I am,")
        time.sleep(1)
        print("\n [__]  Stuck in the                       [__] ")
        print(" |  |               LIDL                  |  | ")
        print("0| 0|                    with you..ooh   0| 0| \n")
        time.sleep(2)
        print(f"-With a bunch of zombies. Seriously, {name}, name a single zombie movie where the supermarkets were safe...")
        time.sleep(2)
        print("You have time to contemplate your mistake as you are torn to pieces.")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
    else:
        time.sleep(1)
        print("You wander out to the parking lot.")
        time.sleep(2)
        print("There are a few cars parked up that look like they won't be missed by their owners.")
        time.sleep(2)
        print("-Because the owners of said cars are lurching about, hungry for human flesh.")
        room7()
def room7():
    global name
    global new_inputs
    time.sleep(2)
    print("Thinking about it, and since this is completely impersonal; you don't feel so bad taking a car from a zombie...")
    time.sleep(2)
    print("Just as you're milling over your now decidedly grey morality, you hear a call for help.")
    time.sleep(2)
    print("What do you do?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print("a: Give up on your humanity completely and go straight for a car.")
    time.sleep(3)
    reply = check_input("b: Make one final bid for your soul and try to provide help for whoever is in need.\n>")
    if reply == "a":
        time.sleep(1)
        print("You figure that a conscience is for people who aren't fleeing for their lives.")
        time.sleep(2)
        print(f"Congratulations {name}, you go and get yourself safely to a mode of transport.")
        time.sleep(3)
        print("-While someone is likely being ripped apart...")
        time.sleep(2)
        print("You absolute monster.")
        room8()
    else:
        time.sleep(1)
        print("You heroically run to the stranger's aid,")
        time.sleep(2)
        print("-and straight into a pack of hungry zombies.")
        time.sleep(2)
        print("As your light goes out, you see the total rando you sacrificed yourself for run about in circles in a blind panic.")
        time.sleep(2)
        print("It's not long before you're both siblings in zombiedom.")
        time.sleep(1)
        print("   ______ ")
        print("  | 0  0 |")
        print("  |_<ii>_|")
        print(" ___|  |___________ __  ")
        print("|______ ___________|__|  ")
        print("|______|__|    ")
        print("  |______|")
        print("  |      |")
        print("  |  |\\  \\ ")
        print("  |  | \\  \\")
        print("  |  |  \\  \\")
        print("  |  |_  \\  \\_")
        print("   \\___\\  \\___\\")
        print("                   ")
        time.sleep(2)
        print("On the bright side, at least your principals are intact.")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
def room8():
    global name
    global new_inputs
    time.sleep(2)
    print("Now that you're committed to being a cold, sociopathic reptile, you figure you might as well take your time partaking in grand theft auto.")
    time.sleep(3)
    print("Looks like the best choices for wheels are a Honda Jazz or a Mercedes Estate.")
    time.sleep(2)
    print(f"Well, go on then {name}. Pick a car to steal.")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print("a: The expensive Mercedes.")
    time.sleep(3)
    reply = check_input("b: The more sensible Honda.\n>")
    if reply == "a":
        time.sleep(1)
        print("I mean, if you're going to survive the total collapse of Human society, you might as well do it in style,")
        time.sleep(2)
        print("nevermind the condemnable actions you just took.")
        time.sleep(2)
        print("You utter fiend.")
        time.sleep(3)
        print("You drown your conscience in a cold drink from the armrest box and a quick go of the heated seat.")
        room9()
    else:
        time.sleep(1)
        print("Ah yes, the reliable Honda Jazz. Top speed, like 50mph.")
        time.sleep(2)
        print("Perfect for driving in the fast lane, backing traffic up for miles.")
        time.sleep(2)
        print("It's broken down... I'd say you get what you pay for, but, you know.")
        time.sleep(2)
        print("The zombies hear you cussing at the car, and they close in.")
        time.sleep(1)
        print("   ______ ")
        print("  | 0  0 |")
        print("  |_<ii>_|")
        print(" ___|  |___________ __  ")
        print("|______ ___________|__|  ")
        print("|______|__|    ")
        print("  |______|")
        print("  |      |")
        print("  |  |\\  \\ ")
        print("  |  | \\  \\")
        print("  |  |  \\  \\")
        print("  |  |_  \\  \\_")
        print("   \\___\\  \\___\\")
        print("                   ")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
def room9():
    global name
    global new_inputs
    time.sleep(2)
    print("You cruise down the main road out of the city.")
    time.sleep(2)
    print("You make decent tracks in 'your' car until you run into what looks like a traffic accident.")
    time.sleep(3)
    print("This isn't all that serious. You could probably force your way through the block if you pushed your car hard enough.")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print("Do you a: Leave your car behind you, escape into the wilderness and start a new life as a hermit,")
    time.sleep(3)
    reply = check_input("or b: Ram the blockade, continuing to the motorway and later to your nanna's?\n>")
    if reply == "a":
        time.sleep(1)
        print("Leaving your degenerate technology and the stress of the great collapse behind you, you clamber off of the road and into the rolling forests beyond.")
        time.sleep(2)
        print("Time for a fresh start, establishing tribal permaculture the way your Mithraic ancestors would have wanted.")
        time.sleep(2)
        print("You set out, proudly blazing a trail through virgin woodland,")
        time.sleep(2)
        print("-and get hopelessly lost as a result.")
        room10()
    else:
        time.sleep(1)
        print("You decide to flippantly disregard to highway-code, adding dangerous driving to your growing list of sins.")
        time.sleep(3)
        print("The car impacts the blockade.")
        time.sleep(2)
        print("The tyres screech.")
        time.sleep(2)
        print("You smell the rubber burn against the tarmac...")
        time.sleep(2)
        for i in range(3):
            i = "..."
            print(i)
            time.sleep(2)
        print("The cars blocking your way slowly move. Looks like they didn't have their parking break on.")
        time.sleep(2)
        print("Before long, you lurch clear of the obstruction.")
        room13()
def room10():
    global name
    global new_inputs
    global inventory
    time.sleep(2)
    print("You are in a woodland clearing.")
    time.sleep(2)
    print("You've been wandering about for what feels like hours.")
    time.sleep(2)
    print(f"What do you want to do now, {name}?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    gen = random.randint(0, 100)
    if len(inventory) == 1:
        new_inputs.append("c")
    print("a: Keep wandering about in the hopes you get un-lost.")
    time.sleep(3)
    if "c" in new_inputs:
        print(f"b: Decide that here is as good a place as any to establish {name}-topia.")
        time.sleep(3)
        reply = check_input("c: Drink the potion you got from the potion seller.\n>")
    else:
        reply = check_input(f"b: Decide that here is as good a place as any to establish {name}-topia.\n>")
    if reply == "a" and gen <=20:
        time.sleep(1)
        print("You carry on into the woods, walking aimlessly.")
        time.sleep(4)
        print("There are no landmarks, no points of reference. The landscape feels like its repeating.")
        time.sleep(1)
        print("\n              /\\                                       \n")
        print("             /  \\                /\\                       ")
        print("            /    \\    _/^^^^^\\_ /  \\                     ")
        print("    ()()()()  ^   \\__/      ^ \\_ ^  \\     ((_))          ")
        print("   ()      ()      /____ ^   ___\\    \\   (_)  (_)         ")
        print("  ()        ()  ^   \\_/      \\_    ^  \\ (_)    (_)       ")
        print("   ()      ()     _/  ^     ^   \\_     (_)      (_)        ")
        print("     ()  ()  ^    /______   ______\\   (_)___  ___(_)       ")
        print("       ||_____  ______\\  | |_____  ________|  |            ")
        print("       ||    |  |        | |     |  |      |  |             ")
        print("       ||   _|  |_       | |    _|  |_     |  |             ")
        print("     __||__            __| |__           __|  |__           ")
        print("                                                          \n")
        time.sleep(2)
        print("Eventually, the sun sets...")
        time.sleep(2)
        print("One moment you can see, the next; the world is enveloped in a pitch black shroud.")
        time.sleep(2)
        print("You fumble around in the dark until finally your legs give in and you land heavily on the forest floor.")
        time.sleep(2)
        for i in range(3):
            i = "..."
            print(i)
            time.sleep(2)
        print("It's cold. You can't feel your body...")
        time.sleep(2)
        print("You hear a rustle in the underbrush...")
        time.sleep(2)
        print("- followed by a bone-chilling growl of an unseen horror.")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
    elif reply == "a" and gen >= 80 and not inventory:
        time.sleep(1)
        print("You carry on into the woods, walking aimlessly.")
        time.sleep(4)
        print("The forest opens up and you see a small cabin.")
        time.sleep(2)
        print("It appears to be a small, rustic shop set up in the middle of the woods.")
        time.sleep(2)
        print("A bell above the door jingles as you enter. You are immediately hit with a powerful smell.")
        time.sleep(3)
        print("The stench from the various bottles and jars is overwhelming.")
        time.sleep(2)
        print("Stood behind the counter is a squat, goblin-like creature in a cloak.")
        time.sleep(2)
        print("You would consider this unusual, but having put up with zombies recently, nothing is out of the ordinary to you...")
        time.sleep(2)
        print("Before you could say anything to the potion seller, he speaks.")
        room12()
    elif reply == "a" and gen > 21 and gen < 80:
        time.sleep(1)
        print("You carry on into the woods, walking aimlessly.")
        time.sleep(4)
        print("As you go on and on among the trunks, the trees begin to look familiar.")
        time.sleep(2)
        print("You realise that you've gone in a massive circle and ended up where you started...")
        room10()
    elif reply == "c" and "potion_a" in inventory:
        time.sleep(1)
        print("You drink the potion.")
        time.sleep(2)
        print("The taste is indescribable.")
        time.sleep(2)
        print("You feel your insides scream at you as a burning sensation overwhelms you.")
        time.sleep(2)
        print("The potion was just too strong for you, traveller. You burst into flames.")
        time.sleep(1)
        print("\n                 /\\    /*\\                 ")
        print("                /+*\\  /+++\\                ")
        print("               /+++\\++*+++*+\\  /*\\        ")
        print("            /+\\*+++++:+++++++\\/*%\\        ")
        print("            %++\\///++=++++==++*+++\\        ")
        print("          //+++++++++++*++++++++++/          ")
        print("          \\*+++====== ::: =====++++\\       ")
        print("        /++++*=+=====::::: ==+++++++/        ")
        print("        /+++++===== ::::::: == =+++%*        ")
        print("        %++++++==== ::::::::: ===+++\\       ")
        print("         \\++===== :::::::::::: ==+++/       ")
        print("           \\*%+=== ::::::::::::: =+%        ")
        print("             %\\\\////////\\\\\\/////*%      ")
        print("                                             \n")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
    elif reply == "c" and "potion_b" in inventory:
        time.sleep(1)
        print("You drink the potion.")
        time.sleep(2)
        print("The taste is indescribable.")
        time.sleep(2)
        print("You feel your insides scream at you as a burning sensation overwhelms you.")
        time.sleep(2)
        print("You feel like you're being pulled inside of yourself.")
        time.sleep(3)
        print("You fall through worlds forgotten, lands long unborn, places that dare not be.")
        time.sleep(2)
        print("An abyss embraces you, whispering its dark secrets, both unseen and unheard.")
        time.sleep(2)
        print("Darknesses between darkness itself seeps through your entire being.")
        time.sleep(2)
        for i in range(5):
            i = "..."
            print(i)
            time.sleep(2)
        print("You are alive...")
        time.sleep(2)
        print("Moreover, all of your limbs are intact... and you're elsewhere...")
        time.sleep(2)
        print("You sit up, brushing off the liquid void congealing on your clothes.")
        time.sleep(3)
        print("Wait a minute...")
        time.sleep(2)
        print("I'd recognise that highland cow anywhere!")
        time.sleep(2)
        print("Terry! It can't be-")
        time.sleep(2)
        print("It is! I have arrived safely at nanna's zombie bunker! Amazing!")
        time.sleep(2)
        print("You relax, safe in the knowledge that you are safe from the zombinoes.")
        time.sleep(2)
        print(f"Well done {name}! You have won!")
        time.sleep(2)
        print("\n                GAME WON!          \n")
        print("            ___                        ")
        print("           |___|                       ")
        print("           |                           ")
        print("      __   |__    __                   ")
        print("     |__|__|__|__|__|                  ")
        print("     |   ________   |      \\ /        ")
        print("     |  |        |  |      [_]_____    ")
        print("     |  |        |  |        |____|\\  ")
        print("     |__|________|__|        |    |    ") 
        print("                                     \n")

        replay()
    else:
        time.sleep(1)
        print("You're not wasting any time here, it's going to go dark soon and you need shelter NOW.")
        time.sleep(2)
        print("You construct a basic shelter out of fallen branches, using ancient knowledge buried deep into your genetic memory...")
        time.sleep(2)
        print("or from that one afternoon in cub scouts.")
        time.sleep(2)
        print("It isn't much, but it provides adequate cover when night finally falls.")
        room11()
def room11():
    global name
    global new_inputs
    time.sleep(2)
    print("When you wake up the following morning, you are both surprised and thankful that you still draw breath.")
    time.sleep(2)
    print("Your stomach growls, and you figure it's about time you set about with your permaculture plan.")
    time.sleep(4)
    print("Time passes, as time often does.")
    time.sleep(2)
    print("What started as a junky little stick fort eventually develops into a rather cozy log cabin.")
    time.sleep(2)
    print("You have found several species of berry to cultivate, and much to your delight the surrounding forest is teeming with rabbits.")
    time.sleep(2)
    print("You get a letter shoved under your door one morning. Something about you owing council tax-?")
    time.sleep(2)
    print("Not even the end of days will stop those vampires...")
    time.sleep(3)
    print(f"Life in {name}-topia is simple, but satisfying. One day you get a knock at the door...")
    time.sleep(2)
    print("It's... A zombie... In a rather colourful outfit.")
    time.sleep(2)
    print("You had actually forgotten that the rest of Humanity was reduced to shambling monstrosities...")
    time.sleep(2)
    print("The saleszombie mumbles something about an exciting new product.")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print("Do you a: Politely point out the sign you put up on your property that reads \"No Solicitors\",")
    time.sleep(3)
    reply = check_input("or b: Listen to what the zombie attempts to say?\n>")
    if reply == "a":
        time.sleep(1)
        print("     ______________    ")
        print("    |              |   ")
        print("    |      NO      |   ")
        print("    |  SOLICITORS  |   ")
        print("    |              |   ")
        print("    |______________|   ")
        print("                       ")
        time.sleep(2)
        print("The zombie gurgles angrily, grumbling something about \"trying to make an un-living\" before accusing you of discriminating against the death-inclined.")
        time.sleep(2)
        print("Before you can get a word in about your liberal values, the zombie lunges at you.")
        time.sleep(1)
        print("   ______ ")
        print("  | 0  0 |")
        print("  |_<ii>_|")
        print(" ___|  |___________ __  ")
        print("|______ ___________|__|  ")
        print("|______|__|    ")
        print("  |______|")
        print("  |      |")
        print("  |  |\\  \\ ")
        print("  |  | \\  \\")
        print("  |  |  \\  \\")
        print("  |  |_  \\  \\_")
        print("   \\___\\  \\___\\")
        print("                   ")
        time.sleep(2)
        print("You get your face bitten off.")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
    elif reply == "b" and "potion_a" in inventory:
        time.sleep(1)
        print("You decide to hear out the saleszombie and ask about the product that it is peddling.")
        time.sleep(2)
        print("The zombie delivers an incredible sales pitch,")
        time.sleep(2)
        print("-at least...")
        time.sleep(1)
        print("you THINK that's what it does. You can't understand a word that passes through its decomposed larynx.")
        time.sleep(3)
        print("You pick up enough to understand that the zombie is talking about Aloe-Vera-?")
        time.sleep(2)
        print("Unsurprisingly, it turns out that it can treat zombification. Is there any blemish it can't fix?")
        time.sleep(2)
        print("Apparently the closest seller of the miracle salve is a mysterious figure that owns a cabin in the forest.")
        time.sleep(2)
        print("That sounds oddly familiar...")
        time.sleep(3)
        print("You retrieve the potion you bought from the enigmatic potion seller and pop the cork.")
        time.sleep(2)
        print("You throw caution to the wind and drink the magical solution.")
        time.sleep(3)
        print("The taste is indescribable.")
        time.sleep(2)
        print("You feel your insides scream at you as a burning sensation overwhelms you.")
        time.sleep(2)
        print("The potion was just too strong for you, traveller. You burst into flames.")
        time.sleep(1)
        print("\n                 /\\    /*\\                 ")
        print("                /+*\\  /+++\\                ")
        print("               /+++\\++*+++*+\\  /*\\        ")
        print("            /+\\*+++++:+++++++\\/*%\\        ")
        print("            %++\\///++=++++==++*+++\\        ")
        print("          //+++++++++++*++++++++++/          ")
        print("          \\*+++====== ::: =====++++\\       ")
        print("        /++++*=+=====::::: ==+++++++/        ")
        print("        /+++++===== ::::::: == =+++%*        ")
        print("        %++++++==== ::::::::: ===+++\\       ")
        print("         \\++===== :::::::::::: ==+++/       ")
        print("           \\*%+=== ::::::::::::: =+%        ")
        print("             %\\\\////////\\\\\\/////*%      ")
        print("                                             \n")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
    elif reply == "b" and "potion_b" in inventory:
        time.sleep(1)
        print("You decide to hear out the saleszombie and ask about the product that it is peddling.")
        time.sleep(2)
        print("The zombie delivers an incredible sales pitch,")
        time.sleep(2)
        print("-at least...")
        time.sleep(1)
        print("you THINK that's what it does. You can't understand a word that passes through its decomposed larynx.")
        time.sleep(3)
        print("You pick up enough to understand that the zombie is talking about Aloe-Vera-?")
        time.sleep(2)
        print("Unsurprisingly, it turns out that it can treat zombification. Is there any blemish it can't fix?")
        time.sleep(2)
        print("Apparently the closest seller of the miracle salve is a mysterious figure that owns a cabin in the forest.")
        time.sleep(2)
        print("That sounds oddly familiar...")
        time.sleep(3)
        print("You retrieve the potion you bought from the enigmatic potion seller and pop the cork.")
        time.sleep(2)
        print("You throw caution to the wind and drink the magical solution.")
        time.sleep(3)
        print("The taste is indescribable.")
        time.sleep(2)
        print("You feel your insides scream at you as a burning sensation overwhelms you.")
        time.sleep(2)
        print("You feel like you're being pulled inside of yourself.")
        time.sleep(3)
        print("You fall through worlds forgotten, lands long unborn, places that dare not be.")
        time.sleep(2)
        print("An abyss embraces you, whispering its dark secrets, both unseen and unheard.")
        time.sleep(2)
        print("Darknesses between darkness itself seeps through your entire being.")
        time.sleep(2)
        for i in range(5):
            i = "..."
            print(i)
            time.sleep(2)
        print("You are alive...")
        time.sleep(2)
        print("Moreover, all of your limbs are intact... and you're elsewhere...")
        time.sleep(2)
        print("You sit up, brushing off the liquid void congealing on your clothes.")
        time.sleep(3)
        print("Wait a minute...")
        time.sleep(2)
        print("I'd recognise that highland cow anywhere!")
        time.sleep(2)
        print("Terry! It's can't be-")
        time.sleep(2)
        print("It is! I have arrived safely at nanna's zombie bunker! Amazing!")
        time.sleep(2)
        print("You relax, safe in the knowledge that you are safe from the zombinoes.")
        time.sleep(2)
        print(f"Well done {name}! You have won!")
        time.sleep(2)
        print("\n                GAME WON!          \n")
        print("            ___                        ")
        print("           |___|                       ")
        print("           |                           ")
        print("      __   |__    __                   ")
        print("     |__|__|__|__|__|                  ")
        print("     |   ________   |      \\ /        ")
        print("     |  |        |  |      [_]_____    ")
        print("     |  |        |  |        |____|\\  ")
        print("     |__|________|__|        |    |    ") 
        print("                                     \n")
        replay()
    else:
        time.sleep(1)
        print("You decide to hear out the saleszombie and ask about the product that it is peddling.")
        time.sleep(2)
        print("The zombie delivers an incredible sales pitch,")
        time.sleep(2)
        print("-at least...")
        time.sleep(1)
        print("you THINK that's what it does. You can't understand a word that passes through its decomposed larynx.")
        time.sleep(3)
        print("You pick up enough to understand that the zombie is talking about Aloe-Vera-?")
        time.sleep(2)
        print("Unsurprisingly, it turns out that it can treat zombification. Is there any blemish it can't fix?")
        time.sleep(2)
        print("Apparently the closest seller of the miracle salve is a mysterious figure that owns a cabin in the forest.")
        time.sleep(2)
        print("You follow the zombie's directions, walking out into the woods until you enter a clearing.")
        time.sleep(2)
        print("You spot what appears to be a small, rustic shop set up in the middle of the woods.")
        time.sleep(2)
        print("A bell above the door jingles as you enter. You are immediately hit with a powerful smell.")
        time.sleep(3)
        print("The stench from the various bottles and jars is overwhelming.")
        time.sleep(2)
        print("Stood behind the counter is a squat, goblin-like creature in a cloak.")
        time.sleep(2)
        print("You would consider this unusual, but having put up with zombies recently, nothing is out of the ordinary to you...")
        time.sleep(2)
        print("Before you could say anything to the potion seller, he speaks.")
        room12()
def room12():
    global name
    global new_inputs
    global inventory
    time.sleep(2)
    print("\n\"My potions are far too strong for you, traveller! I shan't sell you any!\"\n")
    time.sleep(2)
    print("How do you reply?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print("a: Insist to the potion seller that you need his strongest potions.")
    time.sleep(3)
    reply = check_input("b: Call the potion seller a rascal.\n>")
    gen = random.randint(0,100)
    if reply == "a" and gen <= 90:
        time.sleep(1)
        print("You tell the potion seller that you are going into battle, and you need his strongest potions.")
        time.sleep(2)
        seller_reply = [
            "\n\"My strongest potions could kill a dragon, traveller, let alone a knight. You are not worthy of my potions!\"\n",
            "\n\"My potions are meant only for the mightiest! You are clearly not of the mightiest, traveller, but of the weakest!\"\n",
            "\n\"Go elsewhere for your potions, traveller! You are not strong enough for my strongest potions!\"\n",
            "\n\"My strongest potions were meant for Gods, let alone men! You can't handle my strongest potions!\"\n",
            "\n\"You couldn't survive even my weakest potions, traveller! Why would I give you one of my strongest potions?\"\n"
        ]
        print(random.choice(seller_reply))
        room12()
    elif reply == "a" and gen > 90:
        time.sleep(1)
        print("You tell the potion seller that you are going into battle, and you need his strongest potions.")
        time.sleep(2)
        print("The potion seller sneers.")
        time.sleep(2)
        print("\n\"Very well, traveller. You have made your case. Take your potion and begone!\"\n")
        pot_gen = random.randint(0, 100)
        if pot_gen > 50:
            inventory.append("potion_a")
        else:
            inventory.append("potion_b")
        time.sleep(2)
        print("You take your potion, and then your leave of this silly place.")
        room10()
    else:
        time.sleep(1)
        print("You call the potion seller a rascal. A scoundrel that has no respect for knights!")
        time.sleep(2)
        print("No respect for anything...")
        time.sleep(2)
        print("Nothing but his potions!")
        time.sleep(3)
        print("The potion seller's eyes start glowing.")
        time.sleep(2)
        print("He grabs you, pulling your face close to his.")
        time.sleep(2)
        print("In a voice that makes the earth itself shake and your eardrums immediately rupture,")
        time.sleep(2)
        print("he bellows:")
        time.sleep(2)
        print("\n\"WHY WOULD I RESPECT KNIGHTS?\"\n")
        time.sleep(2)
        print("\n\"WHEN MY POTIONS CAN DO ANYTHING THAT THEY CAN.\"\n")
        time.sleep(2)
        print("The world around you fades into darkness as your soul is torn from your body.")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
def room13():
    global name
    global new_inputs
    time.sleep(2)
    print("You get a few more blissful moments of unobstructed driving before you are forced to stop once more.")
    time.sleep(2)
    print("The motorway ahead is utterly gridlocked.")
    time.sleep(3)
    print("Like, imagine rush hour on the M56 and multiply that by ten.")
    time.sleep(2)
    print(f"This is going to be a problem... How will you get past this one, {name}?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print("a: Take your car offroading and try to bypass the blocked motorway.")
    time.sleep(3)
    reply = check_input("b: Attempt to navigate a way through the gridlock.\n>")
    if reply == "a":
        time.sleep(1)
        print("You gun the accelerator and slam through the crash-barrier.")
        time.sleep(2)
        print("The car gets a few amazing seconds of airtime as you perform what can only be described as a pro-gamer move.")
        room16()
    else:
        time.sleep(1)
        print("Funnily enough, it turns out the hard-shoulder is actually mostly clear.")
        time.sleep(3)
        print("I probably should have mentioned that before...")
        room14()
def room14():
    global name
    global new_inputs
    time.sleep(2)
    print("You manage to clear the blockage in the motorway by seriously abusing the hard-shoulder.")
    time.sleep(2)
    print("I suppose you've already stolen a car... What's a little reckless driving, eh?")
    time.sleep(2)
    print("After a very long drive up north, the rolling hills start to give way to untamed and rugged mountains.")
    time.sleep(1)
    print("\n              _________                                         ")
    print("             /         \\       __________                      ")
    print("            /           \\_____/          \\                    ")
    print("   ________/__           \\   /     n      \\                   ")
    print(" _/           \\             /              \\_____________     ")
    print("/      n       \\                       n                 \\    ")
    print("                                                          \\    ")
    print("___________________________________________________________\\   ")
    print("                                                                ")
    print("   ~~                 ~~           ~ ~                          ")
    print("            ~                                  ~~               ")
    print("                                                              \n")
    time.sleep(2)
    print("Alas, the drive was very long and the only petrol station for miles is in Inverness...")
    time.sleep(2)
    print("The car slows to a gentle stop as you go from running on fumes, to not running at all.")
    time.sleep(1)
    print("Seeing as there's nothing else for it, you leave your car and try you luck hoofing it from here on out.")
    time.sleep(2)
    print("Not a few minutes after you begin your long trek to your nanna's, you spot a figure in the road.")
    time.sleep(3)
    print("Oh my goat! It's popular TV presenter Johnathan Ross!")
    time.sleep(2)
    print("You go to shake his hand but suddenly he sinks his teeth into you! Is this a new fad among the media types-?")
    time.sleep(2)
    print("Do you bite him back or-?")
    time.sleep(3)
    print("Oh, wait. No. He's a zombie.")
    time.sleep(2)
    print("This is just like the time you met Ed Sheeran...")
    time.sleep(2)
    print("EXACTLY like that time.")
    time.sleep(2)
    print("Well, zombie Johnathan Ross is wandering off now. How will you proceed?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    print("a: Carry on, facing immanent zombification with nothing but your grit and raw determination.")
    time.sleep(3)
    reply = check_input("b: Give up, conceding defeat and joining the ranks of the undead.\n>")
    if reply == "a":
        time.sleep(1)
        print("You figure that whilst you're still (mostly) Human, you owe it to yourself to keep going.")
        time.sleep(2)
        print("I mean how could this possibly get any worse, right?")
        room15()
    else:
        time.sleep(1)
        print("You figure since now that your whole adventure thus far was for nothing, there was no point going any further.")
        time.sleep(2)
        print("Rather than fighting the cruel hand of fate, you're going to own this.")
        time.sleep(2)
        print("I mean the deceased can even vote now! The sky is the limit!")
        time.sleep(2)
        print("Over the next few minutes, you join the legion of the walking dead.")
        time.sleep(2)
        print("Only you're not a normal zombie...")
        time.sleep(2)
        print("You've become an undead ITV presenter!")
        time.sleep(1)
        print("   ______ ")
        print("  | 0  0 |")
        print("  |_<ii>_|")
        print(" ___|  |___________ __  ")
        print("|______ ___________|__|  ")
        print("|______|__|    ")
        print("  |______|")
        print("  |      |")
        print("  |  |\\  \\ ")
        print("  |  | \\  \\")
        print("  |  |  \\  \\")
        print("  |  |_  \\  \\_")
        print("   \\___\\  \\___\\")
        print("                   ")
        time.sleep(2)
        print("Nevermind all that \"owning your fate\" stuff. This is worse than death.")
        time.sleep(2)
        print("Why did it have to be Johnathan Ross?!")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
def room15():
    global name
    global new_inputs
    time.sleep(2)
    print("You carry on with a head full of hope, shoes full of feet and a cheery outlook on life.")
    time.sleep(2)
    print("Just as the necrosis is beginning to set in, you notice a pair of discarded objects in the road...")
    time.sleep(2)
    print("One of them is a mysterious bottle full of a glowing liquid. It is marked \"PROPERTY OF THE POTION SELLER\". Ominous.")
    time.sleep(2)
    print("The other object is a tube of Aloe-Vera. Just. Aloe-Vera.")
    time.sleep(2)
    print(f"What now, {name}?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    gen = random.randint(0, 100)
    print("a: Take a gamble and drink the mystery juice.")
    time.sleep(3)
    reply = check_input("b: Apply the Aloe-Vera.\n>")
    if reply == "a" and gen > 50:
        time.sleep(1)
        print("You drink the potion.")
        time.sleep(2)
        print("The taste is indescribable.")
        time.sleep(2)
        print("You feel your insides scream at you as a burning sensation overwhelms you.")
        time.sleep(2)
        print("You feel like you're being pulled inside of yourself.")
        time.sleep(3)
        print("You have entered a domain that Gods tremble to contemplate.")
        time.sleep(2)
        print("The universes scream over the perversity of your presence in this un-place.")
        time.sleep(2)
        print("Nightmares of abominations writhing in sunken kingdoms of perpetual ruin cloud your fractured mind.")
        time.sleep(2)
        for i in range(5):
            i = "..."
            print(i)
            time.sleep(2)
        print("You are alive...")
        time.sleep(2)
        print("Moreover, all of your limbs are intact... and you're elsewhere...")
        time.sleep(2)
        print("You sit up, brushing off the liquid void congealing on your clothes.")
        time.sleep(3)
        print("Wait a minute...")
        time.sleep(3)
        print("Unbelievable!")
        time.sleep(2)
        print("The potion sent you straight to nanna's bunker!")
        time.sleep(2)
        print("Whose coming out of the bunker to welcome you-?")
        time.sleep(2)
        print("It's Daniel Craig!")
        time.sleep(2)
        print("D'Craig gives you a martini, shaken, not stirred.")
        time.sleep(1)
        print("\n       / ")
        print(" _____/___")
        print(" \\   0   /")
        print("  \\ /   / ")
        print("   \\   /")
        print("    | |")
        print("    | |")
        print("  __| |__ \n")
        time.sleep(2)
        print("Conveniently, that turns out to be the cure to zombie-ITV-presenter-ness!")
        time.sleep(2)
        print("You regale your nanna and Daniel Craig with the tale of how you got all the way up here.")
        time.sleep(2)
        print("You all share a hearty laugh, safe in the bunker,")
        time.sleep(2)
        print("and you all lived happily ever after. You, your nanna, Daniel Craig, and the three highland cows that your nanna happens to own.")
        time.sleep(2)
        print(f"Congratulations {name}, you made it to safety!")
        time.sleep(2)
        print("\n          GAME WON!    \n")
        print("   ______   ______   ______")
        print("  //   //  //   //       //")
        print(" //   //  //   //    == // ")
        print("//___//  //___//       //\n")
        replay()
    elif reply == "a" and gen < 50:
        time.sleep(1)
        print("You drink the potion.")
        time.sleep(2)
        print("The taste is indescribable.")
        time.sleep(2)
        print("You feel your insides scream at you as a burning sensation overwhelms you.")
        time.sleep(2)
        print("You feel like you're being pulled inside of yourself.")
        time.sleep(3)
        print("You have entered a domain that Gods tremble to contemplate.")
        time.sleep(2)
        print("The universes scream over the perversity of your presence in this un-place.")
        time.sleep(2)
        print("Nightmares of abominations writhing in sunken kingdoms of perpetual ruin cloud your fractured mind.")
        time.sleep(2)
        for i in range(5):
            i = "..."
            print(i)
            time.sleep(2)
        print("You are alive...")
        time.sleep(2)
        print("Moreover, all of your limbs are intact... and you're elsewhere...")
        time.sleep(2)
        print("You sit up, brushing off the liquid void congealing on your clothes.")
        time.sleep(3)
        print("Wait a minute...")
        time.sleep(3)
        print("I'd recognise those FEMA tents anywhere!")
        time.sleep(2)
        print("This is the Fyre festival!")
        time.sleep(2)
        print("The potion took you to the biggest financial blunder of the last decade!")
        time.sleep(2)
        print("You are given your share of the UNICEF rice.")
        time.sleep(2)
        print("You would complain that this is an astonishing example of false advertisement, but you don't think anyone is listening.")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()
    else:
        time.sleep(1)
        print("You rub the Aloe-Vera onto your flaking skin.")
        time.sleep(1)
        print("\n     _ ")
        print("   _| |_")
        print("  |     |")
        print("  |Aloe |")
        print("  |Vera |")
        print("  |     | ")
        print("  |_____|") 
        print("         \n")
        time.sleep(2)
        print("Oddly, you start feeling... much better!")
        time.sleep(2)
        print("Much less corpsely!")
        time.sleep(3)
        print("You're still a zombie, of course. But you're at least not being overcome with cravings for raw meat.")
        time.sleep(2)
        print("Now that your undead stamina is basically limitless, you reckon you could walk to your nanna's from here...")
        time.sleep(4)
        print("Eventually, you see your nanna's zombie bunker on the horizon...")
        time.sleep(2)
        print("Whose coming out of the bunker to welcome you-?")
        time.sleep(2)
        print("It's Daniel Craig!")
        time.sleep(2)
        print("D'Craig gives you a martini, shaken, not stirred.")
        time.sleep(1)
        print("\n       / ")
        print(" _____/___")
        print(" \\   0   /")
        print("  \\ /   / ")
        print("   \\   /")
        print("    | |")
        print("    | |")
        print("  __| |__ \n")
        time.sleep(2)
        print("Conveniently, that turns out to be the cure to zombie-ITV-presenter-ness!")
        time.sleep(2)
        print("You regale your nanna and Daniel Craig with the tale of how you got all the way up here.")
        time.sleep(2)
        print("You all share a hearty laugh, safe in the bunker,")
        time.sleep(2)
        print("and you all lived happily ever after. You, your nanna, Daniel Craig, and the three highland cows that your nanna happens to own.")
        time.sleep(2)
        print(f"Congratulations {name}, you made it to safety!")
        time.sleep(2)
        print("\n          GAME WON!    \n")
        print("   ______   ______   ______")
        print("  //   //  //   //       //")
        print(" //   //  //   //    == // ")
        print("//___//  //___//       //\n")
        replay()
def room16():
    global name
    global new_inputs
    time.sleep(2)
    print("The car immediately slams into a granite outcrop, getting completely totalled in the process.")
    time.sleep(2)
    print(f"Not as easy as the movies, eh {name}?")
    time.sleep(2)
    print("Now that your little stunt has left you out in the middle of nowhere without a vehicle, what do you do?")
    time.sleep(2)
    new_inputs = ["a", "b"]
    gen = random.randint(0, 100)
    print("a: Pray.")
    time.sleep(3)
    reply = check_input("b: Try to see how far you can get on-foot.\n>")
    if reply == "a" and gen > 50:
        time.sleep(1)
        print("You kneel before the granite monolith and reach out to Odinn...")
        time.sleep(3)
        for i in range(3):
            i = "..."
            print(i)
            time.sleep(2)
        print("The Gods answer your call!")
        time.sleep(4)
        print("You awake...")
        time.sleep(2)
        print("You stand atop a mountain bluff.")
        time.sleep(2)
        print("The cares of the world are long behind you, you are in a state of absolute peace.")
        time.sleep(2)
        print("You have awakened from the false dream, emerging into Nirvana.")
        time.sleep(2)
        print("You are a goat.")
        time.sleep(3)
        print("Correction, you have always BEEN a goat. Just now you are realising it.")
        time.sleep(2)
        print("You go and find a nice patch of grass to graze on.")
        time.sleep(2)
        print("\n              GAME WON???     \n")
        print("                                  ")
        print("         /| /|                    ")
        print("        < o o >             ^     ")
        print("         \\   /\\____________/    ")
        print("          \\-/\\             \\   ")
        print("              | _  ____ _ _/      ")
        print("              || ||   || ||       ")
        print("              || ||   || ||       ")
        print("              /\\ /\\   /\\ /\\   ")
        print("                                \n")
        replay()
    elif reply == "a" and gen < 50:
        time.sleep(1)
        print("You kneel before the granite monolith, and reach out to the forces that be...")
        time.sleep(3)
        for i in range(3):
            i = "..."
            print(i)
            time.sleep(2)
        print("The Gods answer your call!")
        time.sleep(4)
        print("You awake...")
        time.sleep(2)
        print("You are surrounded by darkness.")
        time.sleep(2)
        print("Before you can dwell upon your new surroundings, you feel a violent lurch.")
        time.sleep(2)
        print("You are birthed from a sacred Elm tree, dropping rather unceremonially onto the ground.")
        time.sleep(2)
        print("You lie screaming for a while, the existential horror of it all washing over you.")
        time.sleep(3)
        print("When you finally regain your composure, you take a look around.")
        time.sleep(2)
        print("You have made it to the highlands!")
        time.sleep(2)
        print("You can see your nanna's bunker! There are the cows and everything!")
        time.sleep(2)
        print("Fantastic! And all it took was invoking the Elder Gods!")
        time.sleep(3)
        print("Wiping off the excess tree sap, you go to your nanna's bunker.")
        time.sleep(2)
        print(f"Congratulations {name}, you made it to safety!")
        time.sleep(2)
        print("\n     GAME WON!     \n")
        print("                     ")
        print("       mmmmm         ")
        print("      ()0-0()   _    ")
        print("      ()\\_/()  |_|  ")
        print("      __| |__  //    ")
        print("     /  \\ / _\\//   ")
        print("    //|  |  |        ")
        print("   // |__|__|        ")
        print("  |_| /     \\       ")
        print("     /       \\      ")
        print("    /_________\\     ")
        print("      | | | |        ")
        print("      | | | |        ")
        print("      | | | |        ")
        print("     _/ | | \\_      ")
        print("    |___| |___|      ")
        print("                   \n")
        replay()
    else:
        time.sleep(1)
        print("You walk out in the direction of...")
        time.sleep(3)
        print("Well, nowhere.")
        time.sleep(2)
        print("Predictably, the zombies eventually catch up with you.")
        time.sleep(1)
        print("   ______ ")
        print("  | 0  0 |")
        print("  |_<ii>_|")
        print(" ___|  |___________ __  ")
        print("|______ ___________|__|  ")
        print("|______|__|    ")
        print("  |______|")
        print("  |      |")
        print("  |  |\\  \\ ")
        print("  |  | \\  \\")
        print("  |  |  \\  \\")
        print("  |  |_  \\  \\_")
        print("   \\___\\  \\___\\")
        print("                   ")
        time.sleep(2)
        print("Oh well, beats exposure death.")
        time.sleep(2)
        print(" ____   ____   ________  ____     __   __   __ ____ ___    ")
        print("|| ||  ||  || ||  ||  || ||     ||  || \\\\    / ||   || \\ ")
        print("|| __  ||==|| ||  ||  || ||->   ||  ||  \\\\  /  ||-> ||_/  ")
        print("||__|  ||  || ||  ||  || ||__   ||__||   \\\\/   ||__ || \\ \n")
        replay()

def game():
    print("\n\n                         WELCOME     TO                              \n\n")
    time.sleep(2)
    print(" ____   ___  __________  ___  _  _ ____ __    ______ __   __ _____   ")
    print("   //  || || ||  ||  || || ||  ||  ||   ||    ||  || ||\\  || || \\\\  ")
    print("  //   || || ||  ||  || ||-<   ||  ||-> ||    ||==|| || \\ || ||  \\\\ ")
    print(" /____ ||_|| ||  ||  || ||_|| _||_ ||__ ||___ ||  || ||  \\|| ||__//  \n\n")
    time.sleep(2)
    global name
    name = input("Please enter your name.\n>").strip().capitalize()
    time.sleep(1)
    if name == "":
        print("...")
        time.sleep(2)
        print("Okay-? You just sort of stood there silently...")
        time.sleep(2)
        print("Whatever. We'll just roll with it.")
        name = "Weirdo"
    else:
        print(f"Hello {name}!")
    time.sleep(2)
    global new_inputs
    new_inputs = ["y", "n"]
    reply = check_input("Are you ready to begin?\n(y/n)\n>")
    if reply == "y":
        time.sleep(1)
        print("Good luck, and try not to die!")
        room10()
    else:
        time.sleep(1)
        print("That was probably the safer choice.")

game()